### ISSUE TITLE
\citep時に複数著者がet al.で省略されない

### ISSUE THREAD

**Issue by anders-kai** [kosugitti/jecon_jpa#1]
大変ありがたく使わせていただいております。

例えば、sample.bibにある{ekman1990}についてですが、
jecon_jpa.bstで、
FUNCTION {bst.and.others.num} { #3 } として、
sample.texに以下のような追記を行った場合：

\citet{ekman1990}
ではEkman et al. (1990)
と正しく著者が省略されますが

\citep{ekman1990}
では(Ekman, Davidson and Friesen, 1990)となり、
"et al."を使って著者が省略されません。

こちらについては、大量の著者がいる文献を設定し、
FUNCTION {bst.and.others.num}を
#3にしても#6にしても変わりがないことから、
何らかの都合で\citepでは、
著者の省略自体がされないのではないかと拝察します。

**Comment by kosugitti** [comment]
ご連絡ありがとうございます。うわー，私以外にもユーザーいたんだー，と驚いています。

さてご指摘の現象ですが，こちらで確認したところ再現できませんでした。
省略記号になるのは2回目以降の引用です。次のようなコードで実行してもらうと，一度目はフルで，二度目はet.alで表記されますが，いかがでしょうか。

```
例えば文中の引用であれば，\citet{越智2013}のような形にし\citep{ekman1990}，文末の引用であれば次のように書くことになる\citep{Blechman1990,ekman1990}。
```

**Comment by anders-kai** [comment]
２回目以降から省略になる仕様を確認しておりませんでした。
大変失礼いたしました。

また、texに疎いことから、
sample.texのプリアンブルにある通り、
`\usepackage[longnamesfirst]{natbib}`で
`natbib`をロードしていましたが、
`[longnamesfirst]`のオプションを外せば、
１回目の引用から省略されることも確認いたしました。

こちらの理解が十分でなく、
issueとして投げてしまい申し訳ありませんでした。

小杉先生の尽力でlatexで快適に論文を執筆することができます。
本当にありがとうございます。
